dist: trusty

language: php

matrix:
  include:
    - php: 7.4
    - php: 8.0

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs
