dist: trusty

language: php

matrix:
  include:
    - php: 5.6
    - php: 7.0
    - php: 7.1

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer install --prefer-dist

install:
  - travis_retry composer update

script:
  - vendor/bin/phpunit --coverage-text
  - vendor/bin/phpcs --standard=PSR2 --exclude=Squiz.Classes.ValidClassName -n src/
